<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Liga_IT.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="4.0.2.2" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.*" />
    <PackageReference Include="OpenAI" Version="2.1.0" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Liga-IT.Domain\Liga-IT.Domain.csproj" />
  </ItemGroup>

</Project>
